### ISSUE TITLE
Single click, double click, and long press?

### ISSUE THREAD

**Issue by Jeff-Haas** [jsware/able-buttons#3]
Is there a way to combine the existing features to detect, on one button, a single click, a double click, and a long press?

**Comment by JohnScottUK** [comment]
Yes. Each button type adds to the features of simpler buttons. So an AblePullupDoubleClickerButton has double-click, single-click, held and idle features, not just double-click.

**Comment by echedev** [comment]
But it seems that `AblePullupCallbackDoubleClickerButton` does not support callbacks for click and double click. Is this correct?

**Comment by JohnScottUK** [comment]
There isn't an explicit CLICKED_EVENT or DOUBLE_CLICKED_EVENT yet.

A RELEASED_EVENT callback will occur when a click or double-click is completed. This is because a click is a press, followed by a release.

Whether it is a click or double-click can be checked in callback function with isDoubleClicked() and resetDoubleClicked() methods.

```
void eventCallback(Button::CALLBACK_EVENT event, uint8_t id) {
  if(event == Button::RELEASED_EVENT) {
    if(btn.isDoubleClicked()) {
      btn.resetDoubleClicked();
      // Do something for double-click.
    } else {
      // Do something for single-click.
    }
  }
}
```
